# Site settings
title: NylonDLL
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  NylonDLL is a WIP home project designed to aid in using fibers and multithreading.
  It's also a learning project about DLLs, APIs, Multithreading and the like.
baseurl: "/NylonDLL" # the subpath of your site, e.g. /blog/
url: "http://demiguise.github.io" # the base hostname & protocol for your site
twitter_username: AndrewHewitson
github_username:  Demiguise

# Build settings
markdown: kramdown

prose:
	metadata:
    	_posts:
          - name: "category"
            field:
              element: "hidden"
              value: "blog"
          - name: "layout"
            field:
              element: "hidden"
              value: "blog"
          - name: "title"
            field:
              element: "text"
              label: "Title"
              value: ""
